// Generated by gencpp from file riegl/inclinationResponse.msg
// DO NOT EDIT!


#ifndef RIEGL_MESSAGE_INCLINATIONRESPONSE_H
#define RIEGL_MESSAGE_INCLINATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riegl
{
template <class ContainerAllocator>
struct inclinationResponse_
{
  typedef inclinationResponse_<ContainerAllocator> Type;

  inclinationResponse_()
    : roll(0.0)
    , pitch(0.0)  {
    }
  inclinationResponse_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;




  typedef boost::shared_ptr< ::riegl::inclinationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riegl::inclinationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct inclinationResponse_

typedef ::riegl::inclinationResponse_<std::allocator<void> > inclinationResponse;

typedef boost::shared_ptr< ::riegl::inclinationResponse > inclinationResponsePtr;
typedef boost::shared_ptr< ::riegl::inclinationResponse const> inclinationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riegl::inclinationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riegl::inclinationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riegl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'riegl': ['/home/oleffa/catkin_ws/src/riegl/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riegl::inclinationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riegl::inclinationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riegl::inclinationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riegl::inclinationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riegl::inclinationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riegl::inclinationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riegl::inclinationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5aa311af37faead3f9e90f420c9603";
  }

  static const char* value(const ::riegl::inclinationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5aa311af37faeaULL;
  static const uint64_t static_value2 = 0xd3f9e90f420c9603ULL;
};

template<class ContainerAllocator>
struct DataType< ::riegl::inclinationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riegl/inclinationResponse";
  }

  static const char* value(const ::riegl::inclinationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riegl::inclinationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n\
float64 pitch\n\
\n\
";
  }

  static const char* value(const ::riegl::inclinationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riegl::inclinationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inclinationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riegl::inclinationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riegl::inclinationResponse_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIEGL_MESSAGE_INCLINATIONRESPONSE_H
