// Generated by gencpp from file bachelorarbeit/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BACHELORARBEIT_MESSAGE_ADDTWOINTS_H
#define BACHELORARBEIT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <bachelorarbeit/AddTwoIntsRequest.h>
#include <bachelorarbeit/AddTwoIntsResponse.h>


namespace bachelorarbeit
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace bachelorarbeit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bachelorarbeit::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::bachelorarbeit::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::bachelorarbeit::AddTwoInts > {
  static const char* value()
  {
    return "bachelorarbeit/AddTwoInts";
  }

  static const char* value(const ::bachelorarbeit::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::bachelorarbeit::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::bachelorarbeit::AddTwoInts > 
template<>
struct MD5Sum< ::bachelorarbeit::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bachelorarbeit::AddTwoInts >::value();
  }
  static const char* value(const ::bachelorarbeit::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bachelorarbeit::AddTwoIntsRequest> should match 
// service_traits::DataType< ::bachelorarbeit::AddTwoInts > 
template<>
struct DataType< ::bachelorarbeit::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::bachelorarbeit::AddTwoInts >::value();
  }
  static const char* value(const ::bachelorarbeit::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bachelorarbeit::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::bachelorarbeit::AddTwoInts > 
template<>
struct MD5Sum< ::bachelorarbeit::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bachelorarbeit::AddTwoInts >::value();
  }
  static const char* value(const ::bachelorarbeit::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bachelorarbeit::AddTwoIntsResponse> should match 
// service_traits::DataType< ::bachelorarbeit::AddTwoInts > 
template<>
struct DataType< ::bachelorarbeit::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::bachelorarbeit::AddTwoInts >::value();
  }
  static const char* value(const ::bachelorarbeit::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BACHELORARBEIT_MESSAGE_ADDTWOINTS_H
