// Generated by gencpp from file volksbot/ticks.msg
// DO NOT EDIT!


#ifndef VOLKSBOT_MESSAGE_TICKS_H
#define VOLKSBOT_MESSAGE_TICKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace volksbot
{
template <class ContainerAllocator>
struct ticks_
{
  typedef ticks_<ContainerAllocator> Type;

  ticks_()
    : header()
    , left(0)
    , right(0)
    , vx(0.0)
    , vth(0.0)  {
    }
  ticks_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(0)
    , right(0)
    , vx(0.0)
    , vth(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _left_type;
  _left_type left;

   typedef int32_t _right_type;
  _right_type right;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vth_type;
  _vth_type vth;




  typedef boost::shared_ptr< ::volksbot::ticks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::volksbot::ticks_<ContainerAllocator> const> ConstPtr;

}; // struct ticks_

typedef ::volksbot::ticks_<std::allocator<void> > ticks;

typedef boost::shared_ptr< ::volksbot::ticks > ticksPtr;
typedef boost::shared_ptr< ::volksbot::ticks const> ticksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::volksbot::ticks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::volksbot::ticks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace volksbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'volksbot': ['/home/oleffa/catkin_ws/src/volksbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::volksbot::ticks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::volksbot::ticks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volksbot::ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volksbot::ticks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volksbot::ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volksbot::ticks_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::volksbot::ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2672a539e3db4fc52f0208a4f4c3936a";
  }

  static const char* value(const ::volksbot::ticks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2672a539e3db4fc5ULL;
  static const uint64_t static_value2 = 0x2f0208a4f4c3936aULL;
};

template<class ContainerAllocator>
struct DataType< ::volksbot::ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "volksbot/ticks";
  }

  static const char* value(const ::volksbot::ticks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::volksbot::ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 left\n\
int32 right\n\
float32 vx\n\
float32 vth\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::volksbot::ticks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::volksbot::ticks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.vx);
      stream.next(m.vth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ticks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::volksbot::ticks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::volksbot::ticks_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vth: ";
    Printer<float>::stream(s, indent + "  ", v.vth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOLKSBOT_MESSAGE_TICKS_H
