controller_frequency: 15
TrajectoryPlannerROS:
  max_vel_x: 0.80
  min_vel_x: 0.2
  escape_vel: -0.15
  max_rotational_vel: 0.8
  min_in_place_rotational_vel: 0.3

  acc_lim_th: 0.50
  acc_lim_x: 0.80
  acc_lim_y: 0.0

  holonomic_robot: false

  yaw_goal_tolerance: 0.175
  xy_goal_tolerance: 0.15

#path_distance_bias: 0.9
#heading_lookahead: 1.0
goal_distance_bias: 0
