global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 0.50
  publish_frequency: 0.50
  static_map: true
  map_type:   "costmap"
  rolling_window: false
  
  width: 60.0
  height: 60.0
  resolution: 0.10

