local_costmap:
  global_frame: /odom_combined
  robot_base_frame: /base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05
  map_type:   "costmap"
