odom_model_type:            "diff"
odom_alpha5:                0.1
transform_tolerance:        0.1
gui_publish_rate:           10.0
laser_max_beams:            50
min_particles:              300
max_particles:              1000
kld_err:                    0.01
kld_z:                      0.99
odom_alpha1:                1.5
odom_alpha2:                1.2

odom_alpha3:                1.2
odom_alpha4:                1.2
laser_z_hit:                0.98
laser_z_short:              0.05
laser_z_max:                0.05
laser_z_rand:               0.02
laser_sigma_hit:            0.2
laser_lambda_short:         0.1
laser_model_type:           "likelihood_field"

laser_likelihood_max_dist:  2.0
update_min_d:               0.1
#update_min_a:               0.174532925
update_min_a:               0.08
odom_frame_id:              "odom_combined"
resample_interval:          1
transform_tolerance:        0.1
recovery_alpha_slow:        0.0
recovery_alpha_fast:        0.0
initial_pose_x:        -0.12
initial_pose_y:        0.0

