// Generated by gencpp from file volksbot/pose2d.msg
// DO NOT EDIT!


#ifndef VOLKSBOT_MESSAGE_POSE2D_H
#define VOLKSBOT_MESSAGE_POSE2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace volksbot
{
template <class ContainerAllocator>
struct pose2d_
{
  typedef pose2d_<ContainerAllocator> Type;

  pose2d_()
    : x(0.0)
    , z(0.0)
    , theta(0.0)  {
    }
  pose2d_(const ContainerAllocator& _alloc)
    : x(0.0)
    , z(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _z_type;
  _z_type z;

   typedef double _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::volksbot::pose2d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::volksbot::pose2d_<ContainerAllocator> const> ConstPtr;

}; // struct pose2d_

typedef ::volksbot::pose2d_<std::allocator<void> > pose2d;

typedef boost::shared_ptr< ::volksbot::pose2d > pose2dPtr;
typedef boost::shared_ptr< ::volksbot::pose2d const> pose2dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::volksbot::pose2d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::volksbot::pose2d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace volksbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'volksbot': ['/home/oleffa/catkin_ws/src/volksbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::volksbot::pose2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::volksbot::pose2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volksbot::pose2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volksbot::pose2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volksbot::pose2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volksbot::pose2d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::volksbot::pose2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38f95d136be6e97064dca7adba40b51c";
  }

  static const char* value(const ::volksbot::pose2d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38f95d136be6e970ULL;
  static const uint64_t static_value2 = 0x64dca7adba40b51cULL;
};

template<class ContainerAllocator>
struct DataType< ::volksbot::pose2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "volksbot/pose2d";
  }

  static const char* value(const ::volksbot::pose2d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::volksbot::pose2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 z\n\
float64 theta\n\
";
  }

  static const char* value(const ::volksbot::pose2d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::volksbot::pose2d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.z);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose2d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::volksbot::pose2d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::volksbot::pose2d_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOLKSBOT_MESSAGE_POSE2D_H
