// Generated by gencpp from file riegl/angle.msg
// DO NOT EDIT!


#ifndef RIEGL_MESSAGE_ANGLE_H
#define RIEGL_MESSAGE_ANGLE_H

#include <ros/service_traits.h>


#include <riegl/angleRequest.h>
#include <riegl/angleResponse.h>


namespace riegl
{

struct angle
{

typedef angleRequest Request;
typedef angleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct angle
} // namespace riegl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::riegl::angle > {
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::riegl::angle&) { return value(); }
};

template<>
struct DataType< ::riegl::angle > {
  static const char* value()
  {
    return "riegl/angle";
  }

  static const char* value(const ::riegl::angle&) { return value(); }
};


// service_traits::MD5Sum< ::riegl::angleRequest> should match 
// service_traits::MD5Sum< ::riegl::angle > 
template<>
struct MD5Sum< ::riegl::angleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::riegl::angle >::value();
  }
  static const char* value(const ::riegl::angleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::riegl::angleRequest> should match 
// service_traits::DataType< ::riegl::angle > 
template<>
struct DataType< ::riegl::angleRequest>
{
  static const char* value()
  {
    return DataType< ::riegl::angle >::value();
  }
  static const char* value(const ::riegl::angleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::riegl::angleResponse> should match 
// service_traits::MD5Sum< ::riegl::angle > 
template<>
struct MD5Sum< ::riegl::angleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::riegl::angle >::value();
  }
  static const char* value(const ::riegl::angleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::riegl::angleResponse> should match 
// service_traits::DataType< ::riegl::angle > 
template<>
struct DataType< ::riegl::angleResponse>
{
  static const char* value()
  {
    return DataType< ::riegl::angle >::value();
  }
  static const char* value(const ::riegl::angleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIEGL_MESSAGE_ANGLE_H
