// Generated by gencpp from file riegl/selectionRequest.msg
// DO NOT EDIT!


#ifndef RIEGL_MESSAGE_SELECTIONREQUEST_H
#define RIEGL_MESSAGE_SELECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riegl
{
template <class ContainerAllocator>
struct selectionRequest_
{
  typedef selectionRequest_<ContainerAllocator> Type;

  selectionRequest_()
    : type(0)  {
    }
  selectionRequest_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef int64_t _type_type;
  _type_type type;




  typedef boost::shared_ptr< ::riegl::selectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riegl::selectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct selectionRequest_

typedef ::riegl::selectionRequest_<std::allocator<void> > selectionRequest;

typedef boost::shared_ptr< ::riegl::selectionRequest > selectionRequestPtr;
typedef boost::shared_ptr< ::riegl::selectionRequest const> selectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riegl::selectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riegl::selectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riegl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'riegl': ['/home/oleffa/catkin_ws/src/riegl/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riegl::selectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riegl::selectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riegl::selectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riegl::selectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riegl::selectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riegl::selectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riegl::selectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79260b638c2b88f6366fba8cd5157389";
  }

  static const char* value(const ::riegl::selectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79260b638c2b88f6ULL;
  static const uint64_t static_value2 = 0x366fba8cd5157389ULL;
};

template<class ContainerAllocator>
struct DataType< ::riegl::selectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riegl/selectionRequest";
  }

  static const char* value(const ::riegl::selectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riegl::selectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 type\n\
";
  }

  static const char* value(const ::riegl::selectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riegl::selectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct selectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riegl::selectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riegl::selectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int64_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIEGL_MESSAGE_SELECTIONREQUEST_H
