// Generated by gencpp from file riegl/selection.msg
// DO NOT EDIT!


#ifndef RIEGL_MESSAGE_SELECTION_H
#define RIEGL_MESSAGE_SELECTION_H

#include <ros/service_traits.h>


#include <riegl/selectionRequest.h>
#include <riegl/selectionResponse.h>


namespace riegl
{

struct selection
{

typedef selectionRequest Request;
typedef selectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct selection
} // namespace riegl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::riegl::selection > {
  static const char* value()
  {
    return "79260b638c2b88f6366fba8cd5157389";
  }

  static const char* value(const ::riegl::selection&) { return value(); }
};

template<>
struct DataType< ::riegl::selection > {
  static const char* value()
  {
    return "riegl/selection";
  }

  static const char* value(const ::riegl::selection&) { return value(); }
};


// service_traits::MD5Sum< ::riegl::selectionRequest> should match 
// service_traits::MD5Sum< ::riegl::selection > 
template<>
struct MD5Sum< ::riegl::selectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::riegl::selection >::value();
  }
  static const char* value(const ::riegl::selectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::riegl::selectionRequest> should match 
// service_traits::DataType< ::riegl::selection > 
template<>
struct DataType< ::riegl::selectionRequest>
{
  static const char* value()
  {
    return DataType< ::riegl::selection >::value();
  }
  static const char* value(const ::riegl::selectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::riegl::selectionResponse> should match 
// service_traits::MD5Sum< ::riegl::selection > 
template<>
struct MD5Sum< ::riegl::selectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::riegl::selection >::value();
  }
  static const char* value(const ::riegl::selectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::riegl::selectionResponse> should match 
// service_traits::DataType< ::riegl::selection > 
template<>
struct DataType< ::riegl::selectionResponse>
{
  static const char* value()
  {
    return DataType< ::riegl::selection >::value();
  }
  static const char* value(const ::riegl::selectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIEGL_MESSAGE_SELECTION_H
