// Generated by gencpp from file bachelorarbeit/pressed.msg
// DO NOT EDIT!


#ifndef BACHELORARBEIT_MESSAGE_PRESSED_H
#define BACHELORARBEIT_MESSAGE_PRESSED_H

#include <ros/service_traits.h>


#include <bachelorarbeit/pressedRequest.h>
#include <bachelorarbeit/pressedResponse.h>


namespace bachelorarbeit
{

struct pressed
{

typedef pressedRequest Request;
typedef pressedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pressed
} // namespace bachelorarbeit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bachelorarbeit::pressed > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::bachelorarbeit::pressed&) { return value(); }
};

template<>
struct DataType< ::bachelorarbeit::pressed > {
  static const char* value()
  {
    return "bachelorarbeit/pressed";
  }

  static const char* value(const ::bachelorarbeit::pressed&) { return value(); }
};


// service_traits::MD5Sum< ::bachelorarbeit::pressedRequest> should match 
// service_traits::MD5Sum< ::bachelorarbeit::pressed > 
template<>
struct MD5Sum< ::bachelorarbeit::pressedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bachelorarbeit::pressed >::value();
  }
  static const char* value(const ::bachelorarbeit::pressedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bachelorarbeit::pressedRequest> should match 
// service_traits::DataType< ::bachelorarbeit::pressed > 
template<>
struct DataType< ::bachelorarbeit::pressedRequest>
{
  static const char* value()
  {
    return DataType< ::bachelorarbeit::pressed >::value();
  }
  static const char* value(const ::bachelorarbeit::pressedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bachelorarbeit::pressedResponse> should match 
// service_traits::MD5Sum< ::bachelorarbeit::pressed > 
template<>
struct MD5Sum< ::bachelorarbeit::pressedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bachelorarbeit::pressed >::value();
  }
  static const char* value(const ::bachelorarbeit::pressedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bachelorarbeit::pressedResponse> should match 
// service_traits::DataType< ::bachelorarbeit::pressed > 
template<>
struct DataType< ::bachelorarbeit::pressedResponse>
{
  static const char* value()
  {
    return DataType< ::bachelorarbeit::pressed >::value();
  }
  static const char* value(const ::bachelorarbeit::pressedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BACHELORARBEIT_MESSAGE_PRESSED_H
